(lang dune 3.19)

(name calc)

(generate_opam_files true)

(source
 (github username/reponame))

(authors "Jonathan Tran <jonnytran@gmail.com>")

(maintainers "Jonathan Tran <jonnytran@gmail.com>")

(license LICENSE)

(documentation https://url/to/documentation)

(package
 (name calc)
 (synopsis "A short synopsis")
 (description "A longer description")
 (depends ocaml)
 (tags
  ("add topics" "to describe" your project)))

; See the complete stanza docs at https://dune.readthedocs.io/en/stable/reference/dune-project/index.html
